CREATE TABLE IF NOT EXISTS orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    delivered_on TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    telephone  VARCHAR(200),
    email      VARCHAR(512)                            NOT NULL,
    order_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT fk_user_to_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);